server:
  #端口号
  port: 8090
  #项目名，如果不设定，默认是 /
  context-path: /yyy

configuration:
  count: 10
  connections:
    - dataType: SqlServer
      url: jdbc:sqlserver://ip:port;DatabaseName=dataName
      username: dtauser
      password: dtauser
    - dataType: MySql
      url: jdbc:mysql://ip:port/dataName
      username:
      password: